# These are supported funding model platforms

github: [youtubeslgeekshow]
patreon: youtubeslgeekshow
custom: ['https://t.me/SL_bot_zone', 'https://www.youtube.com/channel/UCvYfJcTr8RY72dIapzMqFQA']

